### ISSUE TITLE
Animation Features

### ISSUE THREAD

**Issue by physgun** [ASU-CompMethodsPhysics-PHY494/final-2017-bogus_project#5]
Animation still needs a feature to run probability sum graph either separately or alongside 2D animation

**Comment by orbeckst** [comment]
Look into [`matplotlib.animation`](http://matplotlib.org/api/animation_api.html)
* https://matplotlib.org/2.0.0/examples/animation/index.html
* http://scipy-cookbook.readthedocs.io/items/Matplotlib_Animations.html

**Comment by physgun** [comment]
Added a little number alongside the graph, should work just fine.
